---
abstract: "Reactive programming framework heavily inspired by JavaScript's MobX"
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::AllUtils: '0'
  Test::More: '0'
  Test::Warn: '0'
  strict: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MoobX
provides:
  MoobX:
    file: lib/MoobX.pm
    version: v0.1.1
  MoobX::Array:
    file: lib/MoobX/Array.pm
    version: v0.1.1
  MoobX::Array::Observable:
    file: lib/MoobX/Array/Observable.pm
    version: v0.1.1
  MoobX::Attributes:
    file: lib/MoobX/Attributes.pm
    version: v0.1.1
  MoobX::Hash:
    file: lib/MoobX/Hash.pm
    version: v0.1.1
  MoobX::Hash::Observable:
    file: lib/MoobX/Hash/Observable.pm
    version: v0.1.1
  MoobX::Observer:
    file: lib/MoobX/Observer.pm
    version: v0.1.1
  MoobX::Scalar:
    file: lib/MoobX/Scalar.pm
    version: v0.1.1
  MoobX::Scalar::Observable:
    file: lib/MoobX/Scalar/Observable.pm
    version: v0.1.1
  MoobX::Trait::Observable:
    file: lib/MoobX/Trait/Observable.pm
    version: v0.1.1
  MoobX::Trait::Observer:
    file: lib/MoobX/Trait/Observer.pm
    version: v0.1.1
requires:
  Attribute::Handlers: '0'
  Carp: '0'
  Exporter::Tiny: '0'
  Graph::Directed: '0'
  Module::Runtime: '0'
  Moose: '0'
  Moose::Role: '0'
  Moose::Util: '0'
  MooseX::MungeHas: '0'
  Scalar::Util: '0'
  experimental: '0'
  overload: '0'
  parent: '0'
  perl: v5.20.0
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/MoobX/issues
  homepage: https://github.com/yanick/MoobX
  repository: https://github.com/yanick/MoobX.git
version: 0.1.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_contributors:
  - 'Toby Inkster <github@toby.ink>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
